name: PNN
channels:
  - pytorch
  - default
dependencies:
  - python=3.6.9
  - pytorch=1.2.0
  - matplotlib=3.1.1
  - scikit-learn
  - scipy
  - seaborn=0.9.0
  - torchvision=0.4.0
  - pandas=0.25.1
  - numpy=1.16.5
  - cudatoolkit=9.0
  - pip:
    - astar-tcn --no-dependencies